### ISSUE TITLE
Description file is malformed

### ISSUE THREAD

**Issue by JeroneGagliano** [LBNL-ETA/RMV2.0#1]
Following the install instructions, I get the following:
>devtools::install_github("LBNL-ETA/RMV2.0")
Installation failed: Line starting 'measurement and veri ...' is malformed!

I downloaded the .zip file and edited the Description in the DESCRIPTION file, and install from local which clears the issue. However, loading from local zip does not seem to work. RMV2.0 is not recognized as a package.

**Comment by samirtouzani** [comment]
Thanks for pointing this out! There was an error in the format of the package description. 
I've just updated the repo and you should be able to install the package using the **devtools::install_github("LBNL-ETA/RMV2.0")** command.
