### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zchox** [LBNL-ETA/RMV2.0#12]
I am using Mac OS High Sierra 10.13.3 

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.3.0 (64-bit)

RStudio 1.1.442

when I try 
> devtools::install_github("LBNL-ETA/RMV2.0")

I get this 

Installing RMV2.0
'/usr/local/Cellar/r/3.4.3_1/lib/R/bin/R'  \
  --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/0b/yfv16_4s3g1bsj36cvcln_ph0000gn/T/Rtmpmr5wfk/devtools3a1012c26623/LBNL-ETA-RMV2.0-0b45c89'  \
  --library='/usr/local/lib/R/3.4/site-library'  \
  --install-tests 

ERROR: dependency ‘V8’ is not available for package ‘RMV2.0’
* removing ‘/usr/local/lib/R/3.4/site-library/RMV2.0’
Installation failed: Command failed (1)

**Comment by samirtouzani** [comment]
I couldn't reproduce your error (I've tried on several Mac computers). But it seems that on your mac  devtools::install_github("LBNL-ETA/RMV2.0") can't install automatically the "V8" package. So try to install it before using devtools::install_github("LBNL-ETA/RMV2.0") command.
I hope this will help.

**Comment by zchox** [comment]
@samirtouzani  Thanks for your help,  problem solved,by install V8 first. 
 
before install V8
        install.packages("V8")
need make sure specifically get the v8-315 library 
       brew install v8-315   
otherwise V8 package will not install successfully and get same error message as I got before. 

hope this can help others .

**Comment by samirtouzani** [comment]
Thanks for sharing!
