### ISSUE TITLE
Not able to create new project

### ISSUE THREAD

**Issue by rajthilakm** [LBNL-ETA/RMV2.0#13]
I downloaded and installed RMV2.0 project. The runRMV_UI opens the browser but I am not able to proceed to next step after selecting new project and analysis. The screen grays out. 

I got the following error in my R-studio console :

`Listening on http://127.0.0.1:5332
Warning: Error in : $ operator is invalid for atomic vectors
  46: file.path [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RMV2.0/shiny/guiApp/server.R#102]
  45: <observer> [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RMV2.0/shiny/guiApp/server.R#102]
   2: shiny::runApp
   1: RMV2.0:::runRMV_UI`

<img width="1245" alt="rmv2-screenshot" src="https://user-images.githubusercontent.com/7209204/45790110-1f0df900-bc38-11e8-81e5-6147e38667a5.png">

**Comment by samirtouzani** [comment]
It seems that there is a compatibility problem with the new version of shinyFiles package.

You will need to install the previous version. use the following command:

devtools::install_version("shinyFiles", version = "0.6.2”)

**Comment by joeschmutzler** [comment]
I am having the same issue, and going back to the previous shinyFiles doesn't work, or I am doing it wrong.  Is that a specific process to do this to get this package to work properly?

**Comment by jskromer** [comment]
Regarding->  devtools::install_version("shinyFiles", version = "0.6.2”)

I had luck typing in that code and paying attention to the quotes. Seemed strange, but single quotes around '0.6.2' made it work for me.

**Comment by samirtouzani** [comment]
You first need to install the RMV2.0 then install the previous version of shinyFiles (using the command devtools::install_version("shinyFiles", version = "0.6.2”)). Also note that some users reported that R crashed when they copypasted the command rather than retyping it in the R console.
I hope this will resolve your problem.

**Comment by joeschmutzler** [comment]
The single quotes around 0.6.2 did seem to work like jskromer mentioned.  I'll try typing it in if I still can't work in the program.

**Comment by joeschmutzler** [comment]
I am still having an issue trying to upload a project.  Below is what appears in R Studio when I select my folders.  I have it saved as a .csv file with what looks like the correct headings.  Is there an example file I can download somewhere to see if I am inputting the data correctly?
Thanks,

![rmv2 0 issue](https://user-images.githubusercontent.com/19439179/49766315-c4f66000-fc89-11e8-9c41-2c245c597e76.PNG)

**Comment by samirtouzani** [comment]
Yes! check the data folder (https://github.com/LBNL-ETA/RMV2.0/tree/master/data) you will find examples.
