### ISSUE TITLE
GBM Baseline Modeling FA

### ISSUE THREAD

**Issue by JeroneGagliano** [LBNL-ETA/RMV2.0#2]
I used the temperature only sample pre and post data provided and selected the GBM baseline model using all of the default settings and clicked "Train the Baseline Model".  I received a red alert at the bottom of the screen for all three datasets. In the RStudio Consule, it reported the following:

Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: 'predict' is not an exported object from 'namespace:xgboost'

**Comment by samirtouzani** [comment]
It should be working now.
Thanks

**Comment by JeroneGagliano** [comment]
Great. Is there a more efficient way of updating the RMV2 with this change
other than a full reinstall as there is not a library update for this
package?

Also, related to the custom holiday days off file, is it possible to enter
a date range for some of the days off such as "6/15/16-8/20/16" to account
for academic schedules?

Thanks
Jerone

Jerone Gagliano, PE
607-592-4948
