### ISSUE TITLE
Documentation request - GBM and TOWT model hyper-parameter tuning.

### ISSUE THREAD

**Issue by chrisbalbach** [LBNL-ETA/RMV2.0#4]
When conducting (GBM or TOWT) model hyper-parameter analysis against **more than one baseline model**  (i.e. batch or portfolio analysis),  are the resulting hyper-parameters static across multiple models or are they uniquely determined for each model? 

The existing textual model description is not clear to me on this issue.

**Comment by samirtouzani** [comment]
For the GBM model the optimal hyper-parameters are estimated separately for each model.  Regarding the TOWT there is no cross validation so the same hyper-parameter (timescale for weighting function) will be used for all the models of the batch.
