### ISSUE TITLE
Test vs Training (vs validation?) splits and datasets

### ISSUE THREAD

**Issue by chrisbalbach** [LBNL-ETA/RMV2.0#5]
Documentation issue - User is attempting to compare results from TOWT vs GBM derived models, using the same dataset for baseline and savings data. User is concerned about the issue of (TOWT?) models being trained in a way that will result in 'over-fitting' of the baseline (training?) data. The cross-validation methods of GBM model development are described well in reference papers, but no so much for the TOWT models, in the user's experience.  Are the TOWT models developed using a fixed test/training split of the baseline data or (no test training split at all)?

**Comment by samirtouzani** [comment]
There is no test/training split in the TOWT (no cross validation).  There is always a risk of overfitting (or underfitting)  with models such as TOWT where the level of complexity of the model is fixed (vs automatically determined in GBM). However, our empirical results from different studies have shown that the overfitting is not of a big concern with the TOWT model.
