### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chrisbalbach** [LBNL-ETA/RMV2.0#6]
Feature Request - Consider supporting the capability to estimate savings adherent to IPMVP EQ1b - Normalized Savings, atleast for TOWT approach. This would require the ability to construct models of both the baseline and performance period. Not even sure if this is possible with GBM approach?

**Comment by samirtouzani** [comment]
We are not planing to add this functionality into the GUI. However, you can always use the R baseline modeling functions of the package (as an R script) to build models for both pre and post periods.
