### ISSUE TITLE
Savings Uncertainty

### ISSUE THREAD

**Issue by JeroneGagliano** [LBNL-ETA/RMV2.0#7]
This is not an issue but an inquiry as to when LBNL will include the uncertainty at a given confidence interval for the savings.  I see the code for savings uncertainty is currently deprecated in Savings.R and looks to follow ASHRAE G14.  Is LBNL looking to add uncertainty calculations based on a different methodology that handles autocorrelation and non-linearity?

Thanks
Jerone

**Comment by samirtouzani** [comment]
Our recent findings have shown that the existing methods (including the ASHRAE G14 formulations) to estimate the cumulative savings uncertainty are producing underestimated estimates when high frequency data are considered (e.g. hourly, daily ...), which is non-informative and may be misleading for a decision making process. Thus, we have decided to withdraw the uncertainty estimation from the tool until we find an accurate method.

**Comment by simularis** [comment]
Just some related thoughts.

I've been wondering how to interpret the ASHRAE guideline's formula for autocorrelation (it abuses the notation for predicted values, yhat). I had thought it was meant to request autocorrelation for the observed data, but the code is using the residuals of the model. Thanks for pointing this out. 
https://github.com/LBNL-ETA/RMV2.0/blob/fbfdf2add96b3850a83692ea4d7904caf444d021/R/savings.R#L80

Another option is to try the un-simplified matrix form from Annex B. The simplification is not fully described in the reference (T.A. Reddy and D.E. Claridge (2000)). The xlam add-in ECAM uses a quadratic function of "months" in place of the mystery coefficient 1.26.

https://github.com/LBNL-ETA/RMV2.0/blob/fbfdf2add96b3850a83692ea4d7904caf444d021/R/savings.R#L84
